---
apiVersion: v1
kind: Service
metadata:
  name:  nginx
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx 
  sessionAffinity: None
  type: ClusterIP
